import { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('ppdb_pendaftar', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('(UUID())'))
    table.uuid('tahun_ajaran_id').notNullable()
    table.string('nomor_pendaftaran', 30).notNullable().unique()
    table.string('nisn', 20).notNullable()
    table.string('nama_lengkap', 150).notNullable()
    table.enum('jenis_kelamin', ['L', 'P']).notNullable()
    table.string('tempat_lahir', 100).notNullable()
    table.date('tanggal_lahir').notNullable()
    table.string('agama', 50).nullable()
    table.string('nik', 16).nullable()
    table.text('alamat').notNullable()
    table.string('rt_rw', 20).nullable()
    table.string('kelurahan', 100).nullable()
    table.string('kecamatan', 100).nullable()
    table.string('kota_kabupaten', 100).nullable()
    table.string('provinsi', 100).nullable()
    table.string('kode_pos', 10).nullable()
    table.string('telepon', 20).nullable()
    table.string('email', 150).nullable()
    table.string('asal_sekolah', 200).notNullable()
    table.string('npsn_sekolah', 20).nullable()
    table.text('alamat_sekolah').nullable()
    table.string('nama_ayah', 150).nullable()
    table.string('nik_ayah', 16).nullable()
    table.string('pekerjaan_ayah', 100).nullable()
    table.string('penghasilan_ayah', 50).nullable()
    table.string('telepon_ayah', 20).nullable()
    table.string('nama_ibu', 150).nullable()
    table.string('nik_ibu', 16).nullable()
    table.string('pekerjaan_ibu', 100).nullable()
    table.string('penghasilan_ibu', 50).nullable()
    table.string('telepon_ibu', 20).nullable()
    table.string('nama_wali', 150).nullable()
    table.string('nik_wali', 16).nullable()
    table.string('pekerjaan_wali', 100).nullable()
    table.string('penghasilan_wali', 50).nullable()
    table.string('telepon_wali', 20).nullable()
    table.text('alamat_ortu').nullable()
    table.uuid('pilihan_1_id').notNullable()
    table.uuid('pilihan_2_id').nullable()
    table.enum('jalur', ['zonasi', 'afirmasi', 'prestasi', 'perpindahan']).notNullable()
    table.json('berkas').nullable()
    table.enum('status', ['baru', 'diverifikasi', 'diterima', 'cadangan', 'ditolak']).notNullable().defaultTo('baru')
    table.text('catatan_verifikasi').nullable()
    table.uuid('verified_by').nullable()
    table.timestamp('verified_at').nullable()
    table.timestamp('deleted_at').nullable()
    table.timestamp('created_at').defaultTo(knex.fn.now())
    table.timestamp('updated_at').defaultTo(knex.fn.now())

    table.foreign('tahun_ajaran_id').references('id').inTable('ppdb_tahun_ajaran').onUpdate('CASCADE').onDelete('RESTRICT')
    table.foreign('pilihan_1_id').references('id').inTable('jurusan').onUpdate('CASCADE').onDelete('RESTRICT')
    table.foreign('pilihan_2_id').references('id').inTable('jurusan').onUpdate('CASCADE').onDelete('SET NULL')
    table.foreign('verified_by').references('id').inTable('users').onUpdate('CASCADE').onDelete('SET NULL')
    table.index('tahun_ajaran_id')
    table.index('status')
    table.index('jalur')
    table.index('nisn')
    table.index('nomor_pendaftaran')
    table.index('deleted_at')
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('ppdb_pendaftar')
}